name: Weekly Stats
description: 'Generate weekly stats.'
author: Aaron

inputs:
  GITHUB_TOKEN:
    required: true
    description: 'GITHUB_TOKEN'
  SAVE_TO_REPO:
    required: false
    default: true
    description: 'Whether to save the generated report to the repository.'
  ACCESS_TOKEN:
    required: false
    description: 'ACCESS_TOKEN'
  REPORT_BRANCH:
    required: false
    description: 'Branch to push report.'
    default: 'workflows/weekly-stats'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: calendar
  color: yellow
